name: Pull Request Unit Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Setup Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./api

    - name: Pytest
      run: pytest
      working-directory: ./api
