name: Pull Request Unit Tests

on:
  #psuh event à retirer apres les différents tests
  push:
    branches:
      - feat/pull_request_actions
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name : Setup Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.12'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./api

    - name: Pytest
      run: pytest
      working-directory: ./api
