name: Terraform Destroy

on:
  workflow_dispatch:  
  push:

env:
  TF_LOG: INFO
  TF_INPUT: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        run: |
          echo "Terraform Plan Destroy Output:"
          echo "-------------------"
          terraform plan -destroy -var="subscription_id"=$SUBSCRIPTION_ID -no-color -out=destroy.tfplan

      - name: Terraform Destroy
        id: destroy
        run: terraform apply -auto-approve -input=false -no-color destroy.tfplan