name: Terraform on push main

on:
  push:
    branches:
        - 'dev'
        - 'main'

env:
  TF_LOG: INFO #for getting logs in case of error
  TF_INPUT: false #disables user inputs


jobs:   
  validate-code:  
    uses: ./.github/workflows/terraform-validate.yml
  
  terraform-plan:
    needs: validate-code
    uses: ./.github/workflows/terraform-plan.yml
    with: 
      init-status: ${{ needs.validate-code.outputs.init-status }}


      


