name: Terraform deploy

on:
  workflow_dispatch:
  push:

env:
  TF_LOG: INFO #for getting logs in case of error
  TF_INPUT: false #disables user inputs

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        id: init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check #checks formatting

      - name: Terraform Validate
        # Run even if formatting fails
        if: success() || failure()
        run: terraform validate -no-color #checks syntax

        #Plan section

      - name: Generate plan
        id: plan
        if: success() || failure()
        run: terraform plan -var="subscription_id"=$SUBSCRIPTION_ID -out=build.tfplan

    # Add a comment to pull requests with plan results
      - name: Add Plan Comment
        id: comment
        if: steps.plan.outcome == 'success'
        uses: actions/github-script@v7
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
            Show Plan
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Post Plan Failure 
        if: steps.plan.outcome == 'failure'
        uses: actions/github-script@v6
        env:
          PLAN_FAIL: "terraform\n${{ steps.plan.outputs.stderr }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
            <details><summary>Show Plan Error</summary>
            
            \`\`\`${process.env.PLAN_FAIL}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

            
